### ISSUE TITLE
Is there OAuth 2 support?

### ISSUE THREAD

**Issue by Nusnus** [jpetrucciani/hubspot3#22]
Hey, it's me again :) 

Does the library support running an API that requires OAuth 2 authentication?

EDIT:
I also mean if for example I took care of the authentication myself, can I use the access token instead of API key to run the commands using this library?

Thanks!

**Comment by jpetrucciani** [comment]
You should be able to use an `access_token` and a `refresh_token` instead of an `api_key` when initializing any of the clients!
https://github.com/jpetrucciani/hubspot3/blob/ff5e4b9eca2131ebf8620854c524421331d59d96/hubspot3/base.py#L36-L45

Example:
```python
# instead of:
deals_client = DealsClient(api_key=API_KEY)

# you can do:
deals_client = DealsClient(access_token=ACCESS_TOKEN, refresh_token=REFRESH_TOKEN)
```

You should be able to do this with any of the current clients!

**Comment by Nusnus** [comment]
It doesn't work unfortunately.
It sets the access token in the URL itself instead of in the header so it doesn't work (should have Authorization: Bearer {token} header).

Also, I see the utils.refresh_access_token() uses an outdated endpoint.
See here: https://developers.hubspot.com/docs/methods/oauth2/refresh-access-token

I actually need to use the OAuth authentication method and I really like to use the library so I won't have to manually implement all of the clients you've already implemented.

Would it be possible to release a quick fix for this please?

Thanks!

**Comment by jpetrucciani** [comment]
Hmm, sorry about that! I haven't had to use the OAuth methods yet so that functionality hasn't been touched in a while.

I've pushed some small fixes for that that should work (https://github.com/jpetrucciani/hubspot3/commit/12937eb5e69fb2a93c0fb819f20b96d07ab04f4f), however, I don't currently have access to an OAuth setup to test it out. I've basically just changed it to the newer refresh endpoint, and added that Authorization header instead of appending the access_token to the params.

If you could pull that commit down locally to test and let me know if that works the way you are expecting, I can push that to pip!

**Comment by Nusnus** [comment]
Sure man! Be glad to help - win-win situation here ;) 

Seems there's a bug in the commit - will comment there with the technical part.
Once fixed just LMK and I'll pull the commit and test again.

**Comment by Nusnus** [comment]
Hey @jpetrucciani , your latest commit fixes the bug!
I can finally do `contacts.ContactsClient(access_token=hubspotSession['accessToken'], refresh_token=hubspotSession['refreshToken'], debug=True)` and it works as I expect including building the headers as defined in their official docs (checking with debug=True) and basically everything works exactly as if I used the API key method!

Well done mate!

**Comment by jpetrucciani** [comment]
Awesome! I'll get this fix deployed to pip soon

**Comment by jpetrucciani** [comment]
This should now be on pip as version `3.2.2`!

I'll go ahead and close this issue, but feel free to open it back up if you have any more issues!
